AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30

Naming/VariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
